packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false

onlyBuiltDependencies:
  - '@scarf/scarf'
  - argon2
  - esbuild
  - msgpackr-extract
  - sharp
